services:
  sandbox:
    build:
      context: .
    ports:
      - "8001:8001"
    environment:
      EXPOSE_ADMIN_DOCS: "1"
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
